= Cache de volume BlueXP
:allow-uri-read: 




=== Cache de volume BlueXP

O BlueXP Volume Caching, um recurso do software ONTAP 9, é uma capacidade de cache remoto que simplifica a distribuição de arquivos, reduz a latência da WAN ao aproximar os recursos de onde estão seus usuários e recursos de computação e diminui os custos de largura de banda da WAN. O cache de volume fornece um volume persistente e gravável em um local remoto. Você pode usar o cache de volume do BlueXP para acelerar o acesso aos dados ou para descarregar o tráfego de volumes acessados ​​com frequência. Os volumes de cache são ideais para cargas de trabalho com uso intensivo de leitura, especialmente quando os clientes precisam acessar os mesmos dados repetidamente.

Com o BlueXP Volume Caching, você tem recursos de cache para a nuvem, especificamente para Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP e ambientes locais.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Saiba mais sobre cache de volume"] .
