---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, Volume caching 
summary: O cache de volume fornece um volume persistente e gravável em um local remoto. Você pode usar o cache de volume para acelerar o acesso aos dados ou para descarregar o tráfego de volumes muito acessados. Os volumes de cache são ideais para cargas de trabalho com uso intensivo de leitura, especialmente quando os clientes precisam acessar os mesmos dados repetidamente. 
---
= Gerenciar um cache
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar um cache, alterar a política de exportação, redimensionar um cache e excluir um cache.

Com o cache de volume, você pode atingir estes objetivos:

* Ver detalhes do cache.
* Atribua uma política de exportação diferente a um cache.
* Editar um cache de volume e alterar seu tamanho, etc. Editar terá a opção de visualizar e alterar outras propriedades, e mais propriedades serão adicionadas em editar em versões futuras.
* Redimensione um cache existente com base em uma porcentagem do tamanho do volume original.
* Excluir um cache.




== Ver detalhes do cache

Para cada armazenamento em cache, você pode ver o volume original, o ambiente de trabalho, o volume do cache e muito mais.

.Passos
. Na navegação à esquerda do NetApp Console , selecione *Mobilidade* > *Cache de volume*.
+
Você pode visualizar a lista de volumes de cache criados no sistema de destino.  A lista de caches exibe os detalhes do cache.

. Para filtrar a lista, selecione a opção *Filtrar por +*.
. Selecione uma linha e selecione a opção *Ações…* à direita.
. Selecione *Exibir e editar detalhes*.
. Revise os detalhes.




== Editar um cache

Você pode alterar o nome, o tamanho do volume e a política de exportação de um cache.

.Passos
. Na navegação à esquerda do NetApp Console , selecione *Mobilidade* > *Cache de volume*.
. Selecione uma linha e selecione a opção *Ações…* à direita.
. Selecione *Exibir e editar detalhes*.
. Na guia Configuração básica, opcionalmente, altere o nome do cache e o tamanho do volume do cache.
. Opcionalmente, expanda a guia Acesso ao cache e modifique estes valores:
+
.. O caminho do monte.
.. Uma política de exportação diferente da existente.


. Para alterar os detalhes do compartilhamento SMB/CIFS ou as regras da política de exportação, clique na opção para acessar o NetApp System Manager.
. Selecione *Salvar*.




== Atribuir uma política de exportação de cache diferente

Você pode atribuir uma política de exportação diferente a um cache.

As regras da política de exportação de origem devem ser aplicadas ao cluster de destino.


TIP: Você pode atribuir uma política de exportação existente a um cache.  Você não pode alterar as regras da política de exportação.  Se precisar alterar as políticas de exportação, você pode usar o NetApp System Manager.

.Passos
. Na navegação à esquerda do NetApp Console , selecione *Mobilidade* > *Cache de volume*.
. Selecione uma linha e selecione a opção *Ações…* à direita.
. Selecione *Alterar política de exportação*.
. Selecione a política de exportação que você deseja atribuir ao cache.
. Selecione *Salvar*.




== Redimensionar um cache

Você pode alterar o tamanho do volume do cache com base em uma porcentagem do volume de origem.

.Passos
. Na navegação à esquerda do NetApp Console , selecione *Mobilidade* > *Cache de volume*.
. Selecione uma linha e selecione a opção *Ações…* à direita.
. Selecione *Redimensionar*.
. Insira uma nova porcentagem do tamanho do volume de origem.
+
O volume do cache será redimensionado para a nova porcentagem.

. Selecione *Salvar*.




== Excluir um cache

Se você não precisar mais do cache, poderá excluí-lo.  Isso exclui o relacionamento de cache de volume e exclui o cache de volume de destino.

.Passos
. Na navegação à esquerda do NetApp Console , selecione *Mobilidade* > *Cache de volume*.
. Selecione uma linha e selecione a opção *Ações…* à direita.
. Selecione *Excluir*.
. Marque a caixa.
. Selecione *Excluir*.

