---
sidebar: sidebar 
permalink: release-notes/cache-whats-new.html 
keywords: Volume Caching faq, bluexp, Volume Caching frequently asked questions 
summary: O cache de volume fornece um volume persistente e gravável em um local remoto. Você pode usar o cache de volume para acelerar o acesso aos dados ou para descarregar o tráfego de volumes muito acessados. Os volumes de cache são ideais para cargas de trabalho com uso intensivo de leitura, especialmente quando os clientes precisam acessar os mesmos dados repetidamente. 
---
= O que há de novo no cache de volume?
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubra as novidades em cache de volume.



== 06 de outubro de 2025



=== O cache de volume do BlueXP agora é apenas cache de volume.

O recurso "BlueXP Volume Caching" foi renomeado para "Volume Caching".

Você pode acessá-lo na barra de navegação esquerda do NetApp Console selecionando *Mobilidade* > *Cache de volume*.



=== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, que é altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"] .



== 04 de junho de 2023



=== Cache de volume BlueXP

O BlueXP Volume Caching, um recurso do software ONTAP 9, é uma capacidade de cache remoto que simplifica a distribuição de arquivos, reduz a latência da WAN ao aproximar os recursos de onde estão seus usuários e recursos de computação e diminui os custos de largura de banda da WAN. O cache de volume fornece um volume persistente e gravável em um local remoto. Você pode usar o cache de volume do BlueXP para acelerar o acesso aos dados ou para descarregar o tráfego de volumes acessados ​​com frequência. Os volumes de cache são ideais para cargas de trabalho com uso intensivo de leitura, especialmente quando os clientes precisam acessar os mesmos dados repetidamente.

Com o BlueXP Volume Caching, você tem recursos de cache para a nuvem, especificamente para Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP e ambientes locais.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Saiba mais sobre cache de volume"] .
