---
sidebar: sidebar 
permalink: release-notes/cache-limitations.html 
keywords: Volume Caching, bluexp 
summary: Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do serviço ou que não interoperam corretamente com ele. 
---
= Limitações conhecidas do cache de volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do serviço ou que não interoperam corretamente com ele.



== Limitação na cópia de regras de política de exportação de cache

As regras da política de exportação de cache não são copiadas para o volume de cache nas seguintes situações:

* Quando o sistema do volume de origem for Amazon FSx for NetApp ONTAP ou Cloud Volumes ONTAP e o volume de cache for ONTAP 9.10.1 ou anterior.
* Quando o sistema do volume de origem for qualquer versão do ONTAP e o volume de cache for ONTAP 9.10.1 ou anterior.


Solução alternativa: você deve criar manualmente as regras para o volume de cache.



== A criação do cache falha para VMs de armazenamento com o mesmo nome

Se os clusters de origem e destino usarem VMs de armazenamento com o mesmo nome, o cache não será criado.

Solução alternativa: use nomes diferentes para as VMs de armazenamento de origem e destino.



== Atraso na exibição de políticas de exportação novas ou editadas recentemente

Ao criar um cache, talvez você não consiga ver uma política de exportação criada ou editada recentemente na lista.

Solução alternativa: tente novamente em alguns minutos.



== A criação do cache falha quando o destino tem apenas o protocolo CIFS habilitado

A criação do cache falhará se o cluster de origem ou de destino tiver o ONTAP 9.10.1 ou anterior, e o cluster de destino tiver apenas o protocolo CIFS habilitado.

Solução alternativa: use um cluster de destino executando o ONTAP 9.11.1 ou posterior, ou com os protocolos CIFS e NFS configurados.
